apiVersion: v2
name: karpenter
description: A Helm chart for TKE Karpenter provider.
type: application
version: 0.1.6
appVersion: 0.1.6
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle